include: package:flutter_lints/flutter.yaml

linter:
  rules:
    
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    
    directives_ordering: true

    
    avoid_print: true 
    prefer_final_fields: true 
    always_declare_return_types: true